### ISSUE TITLE
Using `zbus_polkit` on Linux distro without `systemd`

### ISSUE THREAD

**Issue by lukeflo** [dbus2/zbus_polkit#43]
First of all, I'm relatively new to Rust and don't have much experience programming with low level stuff.

At the moment I'm looking for a way to authenticate some single processes run as root in the background of a larger app, which itself runs without root permissions. Using `polkit` seems to be the recommended solution for this.

Thus, I was just trying to run your example from the README.

Calling it with `Connection::system().await?;` finished with an error message saying:

```bash
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.12s
     Running `target/debug/polkit-test`
Error: MethodError(OwnedErrorName("org.freedesktop.PolicyKit1.Error.Failed"), Some("Action org.zbus.BeAwesome is not registered"), Msg { type: Error, serial: 19, sender: UniqueName(":1.0"), reply-serial: 2, body: Str, fds: [] })
```

Calling it with `Connection::session().await?;` finished with an error message saying:

```bash
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.12s
     Running `target/debug/polkit-test`
Error: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name org.freedesktop.PolicyKit1 was not provided by any .service files"), Msg { type: Error, serial: 3, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 2, body: Str, fds: [] })
```

The error message `The name org.freedesktop.PolicyKit1 was not provided by any .service files` made me ponder (even if I know, calling `system()` is needed to speak to `org.freedesktop.PolicyKit1`.

There are absolute zero **`.service`** files on my system since I'm not running `systemd` for managing services. Instead I'm using Void Linux with `runit` for service management.

Is `zbus` only compatible with `systemd`? Or am I missing something very obvious about it? Sorry, if that might be an easy question. As said, I've not much experience with this stuff...

**Comment by zeenix** [comment]
> First of all, I'm relatively new to Rust

That's OK. We all start somewhere. Having said that, I would highly recommend you familiarise yourself with Rust essentials before doing anything complicated or even useful with it. I always recommend folks new to Rust, to read and follow the advice in [this blog post](https://ferrous-systems.com/blog/mindsets-and-expectations/).

> There are absolute zero **`.service`** files on my system since I'm not running `systemd` for managing services. Instead I'm using Void Linux with `runit` for service management.

You said you're new to low-level programming. So I also strongly recommend you use a typical Linux distro that has the modern essentials like systemd.

> Calling it with `Connection::system().await?;` finished with an error message saying:

The error you pasted is mostly definitely not form this call. It's from a call to polkit after this step. Either there is no polkit installed on the system or it's not running. Typically the bus launches the service automatically for you so I'm betting it's either the former or you Linux distro is being strange or just broken. 

Moreover, this is not at all specific to zbus in any way. zbus_polkit just provide ready-made API to talk to polkit and that's it. You are getting error on zbus connecting to the system bus itself. 

> Is `zbus` only compatible with `systemd`?

No. zbus has nothing to do with systemd at all. It only talks D-Bus.

---

Closing this as this is not an issue in zbus_polkit.
